"use client";
import { useRouter, useSearchParams } from "next/navigation";
import React, { useEffect, useRef, useState } from "react";
import axios from "axios";
type Props = {};

const SuccessPage = (props: Props) => {
  const router = useRouter();
  const query = useSearchParams();

  const [responseMessage, setResponseMessage] = useState("");
  const url = "https://uat.esewa.com.np/epay/transrec";

  const formRef = useRef<HTMLFormElement>(null);

  useEffect(() => {
    if (formRef.current) {
      formRef.current.submit();
    }
  }, []);

  return (
    <div>
      <form
        ref={formRef}
        action="https://uat.esewa.com.np/epay/transrec"
        method="GET"
      >
        <input value={query.get("amt") || 0} name="amt" type="hidden" />
        <input value="EPAYTEST" name="scd" type="hidden" />
        <input value={query.get("oid") || ""} name="pid" type="hidden" />
        <input value={query.get("refId") || ""} name="rid" type="hidden" />
        {/* <input value="Submit" type="submit" /> */}
      </form>
    </div>
  );
};

export default SuccessPage;
// # oid=1684338424204--7.380424113313042--1684338424204-fjlkawf-SuzanRana&amt=100.0&refId=0005JQ7
// amt	Total payment amount of product or service
// scd	Merchant code provided by eSewa
// pid	A unique ID of product or item or ticket etc generated by merchant for payment
// rid
