'use client';
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import axios from "axios";
type Props = {};

const SuccessPage = (props: Props) => {
  const { query } = useRouter();
  const [responseMessage, setResponseMessage] = useState("");
  const url = "https://uat.esewa.com.np/epay/transrec";

  useEffect(() => {
    const data = {
      amt: query?.["amt"],
      scd: "EPAYTEST",
      pid: query?.["oid"],
      rid: query?.["refId"],
    };
    const fetchEsewa = async () => {
      return await axios
        .post(url, data)
        .then((res) => res.data)
        .catch((error) => {
          console.log("ERROR", error);
        });
    };
    const d = fetchEsewa();
    setResponseMessage(d as any);
    console.log("first");
  }, []);

  if (!query?.["oid"] || !query?.["amt"] || !query?.["refId"]) {
    return <p>Invalid success URL.</p>;
  }

  return (
    <div>
      SuccessPage: <pre>{responseMessage}</pre>
    </div>
  );
};

export default SuccessPage;
// # oid=1684338424204--7.380424113313042--1684338424204-fjlkawf-SuzanRana&amt=100.0&refId=0005JQ7
// amt	Total payment amount of product or service
// scd	Merchant code provided by eSewa
// pid	A unique ID of product or item or ticket etc generated by merchant for payment
// rid
